title: Markdown Rise
# description: Markdown Rise is a powerful extension for the markdown
description: Markdown Rise - расширение возможностей markdown

remote_theme: just-the-docs/just-the-docs@v0.10.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

show_downloads: true # ["true" or "false" (unquoted) to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]

favicon_ico: "/assets/images/markdown-rise-dark-orange-filled.ico"


#----------------------------------------------------------------------------
# Search - https://just-the-docs.github.io/just-the-docs/docs/configuration/#search

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  # button: false
  button: true
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  # focus_shortcut_key: 'k'


#----------------------------------------------------------------------------
# Aux links - https://just-the-docs.github.io/just-the-docs/docs/configuration/#aux-links

aux_links:
  "Aux Links - Just the Docs on GitHub":
    - "//github.com/just-the-docs/just-the-docs"
  "Markdown Rise":
    - "//markdown-rise.ru/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false


#----------------------------------------------------------------------------
# Navigation sidebar - https://just-the-docs.github.io/just-the-docs/docs/configuration/#navigation-sidebar

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true


#----------------------------------------------------------------------------
# Heading anchor links - https://just-the-docs.github.io/just-the-docs/docs/configuration/#heading-anchor-links

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true


#----------------------------------------------------------------------------
# External Links - https://just-the-docs.github.io/just-the-docs/docs/navigation/main/external/#external-links

# External navigation links
nav_external_links:
  - title: Just the Docs on GitHub
    url: https://github.com/just-the-docs/just-the-docs
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false


#----------------------------------------------------------------------------
# Use a custom scheme - https://just-the-docs.github.io/just-the-docs/docs/customization/#use-a-custom-scheme

color_scheme: mdr
# color_scheme: dark


# $link-color: $blue-000;


